behaviors:
  Player:
    trainer_type: ppo
    max_steps: 5e6
    time_horizon: 64
    summary_freq: 10000
    keep_checkpoints: 2
    checkpoint_interval: 50000
    threaded: false
    
    hyperparameters:
      batch_size: 512
      buffer_size: 10240
      learning_rate: 3e-4
      learning_rate_schedule: linear
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3

    network_settings:
      num_layers: 2
      hidden_units: 128
      normalize: false
      vis_encoder_type: simple

    reward_signals:
      extrinsic:
        strength: 0.75
        gamma: 0.85
      curiosity:
        strength: 0.02
        gamma: 0.99
        encoding_size: 256
        learning_rate : 1e-4





